version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      # - API_ENDPOINT_STAGING=http://staging-api.example.com
      - NEXT_PUBLIC_SITE_URL=https://testing.meteryard.com/api/v1
